#ifndef _BIZ_ERR_H_
#define _BIZ_ERR_H_

#define ERR_BIZ_SUCCESSFUL					 0
#define ERR_BIZ_UNSUCCESSFUL                -31
#define ERR_BIZ_NOT_INITIALIZED				-32
#define ERR_BIZ_ALREADY_INITIALIZED			-33
#define ERR_BIZ_TIME_OUT					-34
#define ERR_BIZ_INVALID_PARAMETER			-35
#define ERR_BIZ_NET_NAME_RESOLVE_FAILED		-36
#define ERR_BIZ_INSUFFICIENT_RESOURC		-37
#define ERR_BIZ_TOO_FAST_INPUT			    -38
#define ERR_BIZ_NET_PORT_BIND_FAILED		    -39
#define ERR_BIZ_NOT_LOGIN                   -40
#define ERR_BIZ_ACCOUNT_ALREADY_EXIST		-41
#define ERR_BIZ_INVALID_USER				-42
#define ERR_BIZ_NO_RESULT					-43
#define ERR_BIZ_INVALID_VERSION             -44
#define ERR_BIZ_INVALID_SERVICE             -45
#define ERR_BIZ_INVALID_BILLING             -46
#define ERR_BIZ_ALREADY_LOGOUT				-47
#define ERR_BIZ_INCORECT_PACKET				-48
#define ERR_BIZ_SVR_OPERATION_FAILED        -49
#define ERR_BIZ_ID_EXCEED_LIMITATION        -50
#define ERR_BIZ_INVALID_IDPRE               -51
#define ERR_BIZ_INVALID_BIZSTR              -52
#define ERR_BIZ_INVALID_CONF                -53
#define ERR_BIZ_SERVER_BUSY					-54  
#define ERR_BIZ_MTEL_ALREADY_EXIST			-55  
#define ERR_BIZ_MAIL_ALREADY_EXIST			-56 
#define ERR_BIZ_UID_UNEXISTED				-57 
#define ERR_BIZ_UID_AUTH_UNMEETED			-58 
#define ERR_BIZ_ACCOUNT_INACTIVE			-59 
#define ERR_BIZ_INVALID_SESSION				-60 
#define ERR_BIZ_ALREADY_LOGOUT_FORCED		-61
#define ERR_BIZ_SERVER_DISCONNECTED			-62
#define ERR_BIZ_INCORRECT_PWD				-63
#define ERR_BIZ_LIMITED_PRIVILEG			-64
#define ERR_BIZ_USER_OFFLINE				-65
#define ERR_BIZ_FELLOW_UNEXIST				-66
#define ERR_BIZ_PACKET_CREATE_FAILED		-67
#define ERR_BIZ_NET_SOCKET_WRITE_FAILED				-68
#define ERR_BIZ_NET_SOCKET_READ_FAILED				-69
#define ERR_BIZ_NET_SOCKET_CREATE_FAILED				-70
#define ERR_BIZ_NET_SERVER_CONNECT_FAILED				-71
#define ERR_BIZ_SELECT_ON_ERROR				-72
#define ERR_BIZ_APP_NOT_REGISTE				-73
#define ERR_BIZ_UNKNOWN_CMD				-74



#endif

