#ifndef _BP_ERROR_H_
#define _BP_ERROR_H_
//p2p error define
#define ERROR_PPPP_SUCCESSFUL						0
#define ERROR_PPPP_NOT_INITIALIZED					-1
#define ERROR_PPPP_ALREADY_INITIALIZED				-2
#define ERROR_PPPP_TIME_OUT							-3
#define ERROR_PPPP_INVALID_ID						-4
#define ERROR_PPPP_INVALID_PARAMETER				-5
#define ERROR_PPPP_DEVICE_NOT_ONLINE				-6
#define ERROR_PPPP_FAIL_TO_RESOLVE_NAME				-7
#define ERROR_PPPP_INVALID_PREFIX					-8
#define ERROR_PPPP_ID_OUT_OF_DATE					-9
#define ERROR_PPPP_NO_RELAY_SERVER_AVAILABLE		-10
#define ERROR_PPPP_INVALID_SESSION_HANDLE			-11
#define ERROR_PPPP_SESSION_CLOSED_REMOTE			-12
#define ERROR_PPPP_SESSION_CLOSED_TIMEOUT			-13
#define ERROR_PPPP_SESSION_CLOSED_CALLED			-14
#define ERROR_PPPP_REMOTE_SITE_BUFFER_FULL			-15
#define ERROR_PPPP_USER_LISTEN_BREAK				-16
#define ERROR_PPPP_MAX_SESSION						-17
#define ERROR_PPPP_UDP_PORT_BIND_FAILED				-18
#define ERROR_PPPP_USER_CONNECT_BREAK				-19
#define ERROR_PPPP_NO_CONF_FILE 					-20
#define ERROR_PPPP_NO_DB_CONNECTION 				-21
#define ERROR_PPPP_INSUFFICIENT_RESOURC 			-22
#define ERROR_PPPP_INVALID_CONFSTRING				-23
#define ERROR_PPPP_NO_NETCARD						-24
#define ERROR_PPPP_CONFFILE_CREATE_FAILED			-25
#define ERROR_PPPP_UNAUTHORIZ						-26
#define ERROR_PPPP_NOT_LOGIN 						-27
#define ERROR_PPPP_DB_OPERATION_FAILED				-28
#define ERROR_PPPP_SENDPKT_FAILED                   -29
#define ERROR_PPPP_BUFFER_ERROR                     -30

//biz error define
#define ERR_BIZ_SUCCESSFUL					 0
#define ERR_BIZ_UNSUCCESSFUL                -31
#define ERR_BIZ_NOT_INITIALIZED				-32
#define ERR_BIZ_ALREADY_INITIALIZED			-33
#define ERR_BIZ_TIME_OUT					-34
#define ERR_BIZ_INVALID_PARAMETER			-35
#define ERR_BIZ_FAIL_TO_RESOLVE_NAME		-36
#define ERR_BIZ_INSUFFICIENT_RESOURC		-37
#define ERR_BIZ_TOO_FAST_INPUT			    -38
#define ERR_BIZ_PORT_BIND_FAILED		    -39
#define ERR_BIZ_NOT_LOGIN                   -40
#define ERR_BIZ_ACCOUNT_ALREADY_EXIST		-41
#define ERR_BIZ_INVALID_USER				-42
#define ERR_BIZ_NO_RESULT					-43
#define ERR_BIZ_INVALID_VERSION             -44
#define ERR_BIZ_INVALID_SERVICE             -45
#define ERR_BIZ_INVALID_BILLING             -46
#define ERR_BIZ_ALREADY_LOGOUT				-47
#define ERR_BIZ_INCORECT_PACKET				-48
#define ERR_BIZ_SVR_OPERATION_FAILED        -49
#define ERR_BIZ_ID_EXCEED_LIMITATION        -50
#define ERR_BIZ_INVALID_IDPRE               -51
#define ERR_BIZ_INVALID_BIZSTR              -52
#define ERR_BIZ_INVALID_CONF                -53
#define ERR_BIZ_SERVER_BUSY					-54  
#define ERR_BIZ_MTEL_ALREADY_EXIST			-55  
#define ERR_BIZ_MAIL_ALREADY_EXIST			-56 
#define ERR_BIZ_UID_UNEXISTED				-57 
#define ERR_BIZ_UID_AUTH_UNMEETED			-58 
#define ERR_BIZ_ACCOUNT_UNACTIVE			-59 
#define ERR_BIZ_INVALID_SESSION				-60 
#define ERR_BIZ_ALREADY_LOGOUT_FORCED		-61
#define ERR_BIZ_SERVER_DISCONNECTED			-62
#define ERR_BIZ_PACKET_CREATE_FAILED		-63



#endif

